#!/bin/bash

archs=(
    "resnet18"
    "vgg8"
    "sfcn"
    "glt"
)

if [[ $# -gt 0 ]]; then
    archs=("$@")
fi

configs=(
    ""
    "--sample over"
    "--sample under"
    "--sample scale-up"
    "--sample scale-down"
    "--reweight inv"
    "--reweight sqrt_inv"
    "--reweight inv --lds"
    "--reweight sqrt_inv --lds"
    "--fds"
    "--reweight inv --fds"
    "--reweight sqrt_inv --fds"
    "--reweight inv --lds --fds"
    "--reweight sqrt_inv --lds --fds"
)

for arch in "${archs[@]}"; do
    for config in "${configs[@]}"; do
        command="sbatch slurm $arch $config"
        echo "Running: $command"
        eval "$command"
    done
done
